name: Publish Package to npmjs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load AWS credentials
        id: load-aws-credentials
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          NPM_TOKEN: op://CI-CD/NPM-datafoldnpm-Token/credential

      - uses: actions/setup-node@v3
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@datafoldcom'

      - run: npm ci

      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
